export enum AppRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  CONTENT_EDITOR = 'CONTENT_EDITOR',
  INSTITUTION_USER = 'INSTITUTION_USER',
  RANKING_REVIEWER = 'RANKING_REVIEWER',
}